apiVersion: apps/v1
kind: Deployment

metadata:
  name: jobportal-deployment
  labels:
    app: jobportal

spec:
  replicas: 2

  selector:
    matchLabels:
      app: jobportal

  template:
    metadata:
      labels:
        app: jobportal

    spec:
      containers:
        - name: jobportal-container
          image: sharmaanchal01/jobportal:latest

          ports:
            - containerPort: 80

          env:
            - name: VITE_APP_NAME
              valueFrom:
                configMapKeyRef:
                  name: jobportal-config
                  key: VITE_APP_NAME