apiVersion: v1
kind: Config
preferences: {}
clusters:
- cluster:
    certificate-authority: C:\Users\Aanchal\.minikube\ca.crt
    server: https://127.0.0.1:57401
  name: minikube

contexts:
- context:
    cluster: minikube
    namespace: default
    user: minikube
  name: minikube

current-context: minikube

users:
- name: minikube
  user:
    client-certificate: C:\Users\Aanchal\.minikube\profiles\minikube\client.crt
    client-key: C:\Users\Aanchal\.minikube\profiles\minikube\client.key